blank_issues_enabled: false
contact_links:
  - name: ❓ Genel Soru
    url: mailto:onurturan.t@gmail.com
    about: Genel sorular ve sohbetler için  mail atın.
    description: Genel sorular ve sohbetler için  mail atın.