name:  Logic Anomaly
description: Kodun mant覺ksal olarak hatal覺 癟al覺t覺覺 durumlar覺 bildirin
title: "[ANOMALY] "
labels: [logic-anomaly]
body:
  - type: markdown
    attributes:
      value: |
        Kodun beklenmedik veya hatal覺 癟al覺t覺覺n覺 m覺 fark ettiniz? L羹tfen detayland覺r覺n.

  - type: textarea
    id: anomaly_description
    attributes:
      label: Anomali A癟覺klamas覺
      placeholder: Ne bekliyordunuz, ne oldu?
    validations:
      required: true

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: Beklenen vs Mevcut Davran覺
      placeholder: |
        Beklenen:
        Ger癟ekleen:
    validations:
      required: true

  - type: textarea
    id: code_example
    attributes:
      label: 襤lgili Kod veya Ak覺
      description: Kod par癟as覺, pseudocode veya ilgili dosya yap覺s覺n覺 ekleyin
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Etkileri
      description: Bu mant覺ksal hata ne gibi sonu癟lara neden oluyor?
    validations:
      required: false
